name: cloud_dw_datavault
version: 1.0.0
config-version: 2

profile: cloud_dw_duckdb

model-paths: ["models"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
target-path: "target"  # where dbt stores compiled SQL
clean-targets: ["target", "dbt_packages"]

models:
  cloud_dw_datavault:
    +materialized: view
    raw_vault:
      +schema: raw_vault
    marts:
      +schema: marts
