name: cloud_dw_datavault
version: 1.0.0
config-version: 2

profile: cloud_dw_duckdb

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cloud_dw_datavault:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging", "raw"]
    raw_vault:
      +materialized: view
      +schema: raw_vault
      +tags: ["raw_vault"]
    business_vault:
      +tags: ["business_vault"]
      hubs:
        +materialized: table
        +schema: main
      links:
        +materialized: table
        +schema: main
      satellites:
        +materialized: incremental
        +schema: main
        +tags: ["incremental", "satellite"]
      pit:
        +materialized: table
        +schema: main
        +tags: ["pit"]
    marts:
      +materialized: view
      +schema: marts
      +tags: ["mart", "analytics"]
